# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDescriptors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.TextField()),
                ('content_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.ContentDescriptors')),
            ],
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField(unique=True)),
                ('game_name', models.TextField()),
                ('json_url', models.TextField()),
                ('image_url', models.TextField()),
                ('age_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GamePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('base_price', models.FloatField(default=0.0)),
                ('base_discount', models.IntegerField(default=0)),
                ('plus_discount', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('psn_rating', models.FloatField(default=0.0)),
                ('psn_rating_count', models.IntegerField(default=0)),
                ('mcritic_critic_rating', models.FloatField(default=0.0)),
                ('mcritic_critic_rating_count', models.IntegerField(default=0)),
                ('mcritic_user_rating', models.FloatField(default=0.0)),
                ('mcritic_user_rating_count', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_score', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.TextField(unique=True)),
                ('last_updated', models.DateTimeField()),
                ('total_results', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamecontent',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList'),
        ),
    ]
