# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList'),
        ),
        migrations.AlterField(
            model_name='gameratings',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList'),
        ),
        migrations.AlterField(
            model_name='gamevalue',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.GameList'),
        ),
    ]
