# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0002_auto_20170416_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
