# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0004_gamelist_library_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameratings',
            old_name='psn_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='gameratings',
            old_name='psn_rating_count',
            new_name='rating_count',
        ),
        migrations.RemoveField(
            model_name='gameratings',
            name='mcritic_critic_rating',
        ),
        migrations.RemoveField(
            model_name='gameratings',
            name='mcritic_critic_rating_count',
        ),
        migrations.RemoveField(
            model_name='gameratings',
            name='mcritic_user_rating',
        ),
        migrations.RemoveField(
            model_name='gameratings',
            name='mcritic_user_rating_count',
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='library_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnvalue.Library'),
        ),
    ]
