# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0006_auto_20170603_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameratings',
            name='weighted_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
