# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0008_remove_library_total_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprice',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='gameratings',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='gamevalue',
            name='game_id',
        ),
        migrations.RenameField(
            model_name='gamelist',
            old_name='library_name',
            new_name='library_id',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='base_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='plus_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='value_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='weighted_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='library',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='GamePrice',
        ),
        migrations.DeleteModel(
            name='GameRatings',
        ),
        migrations.DeleteModel(
            name='GameValue',
        ),
    ]
