# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0009_auto_20170626_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelist',
            old_name='library_id',
            new_name='library_fk',
        ),
    ]
