# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0010_auto_20170701_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelist',
            old_name='discount_price',
            new_name='net_price',
        ),
    ]
