# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0011_auto_20170701_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelist',
            old_name='net_price',
            new_name='plus_price',
        ),
        migrations.RenameField(
            model_name='gamelist',
            old_name='value_score',
            new_name='plus_value_score',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='base_value_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
