# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0012_auto_20170809_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdescriptors',
            name='content_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='gamecontent',
            unique_together=set([('game_id', 'content_name')]),
        ),
    ]
