# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-09 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0013_auto_20170809_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecontent',
            old_name='content_name',
            new_name='content_descriptor_fk',
        ),
        migrations.RenameField(
            model_name='gamecontent',
            old_name='game_id',
            new_name='game_id_fk',
        ),
        migrations.AlterUniqueTogether(
            name='gamecontent',
            unique_together=set([('game_id_fk', 'content_descriptor_fk')]),
        ),
    ]
