# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-08 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0016_auto_20171003_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='image_datastore_url',
            field=models.TextField(blank=True),
        ),
    ]
