# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-08 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psnvalue', '0017_gamelist_image_datastore_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelist',
            name='image_data',
        ),
    ]
